
snake: snakes_and_ladders.c linked_list.c linked_list.h markov_chain.c markov_chain.h
	gcc -Wextra -Wall -Wvla -std=c99 snakes_and_ladders.c linked_list.c markov_chain.c -o snakes_and_ladders
tweets: tweets_generator.c linked_list.c linked_list.h markov_chain.c markov_chain.h
	gcc -Wextra -Wall -Wvla -std=c99 tweets_generator.c linked_list.c markov_chain.c -o tweets_generator